"""add claims table

Revision ID: 0060598110a3
Revises: 9f846510cfe4
Create Date: 2026-08-06 18:24:07.391258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0060598110a3'
down_revision: Union[str, None] = '9f846510cfe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contradicting_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fact_check_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_research_run_id'), 'claims', ['research_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_research_run_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
