"""add reports table

Revision ID: 9f846510cfe4
Revises: 3f1c8a7e9b20
Create Date: 2026-08-06 13:13:21.454470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f846510cfe4'
down_revision: Union[str, None] = '3f1c8a7e9b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('overall_confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_research_run_id'), 'reports', ['research_run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_research_run_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
